---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cartsloadgen
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cartsloadgen
    spec:
      containers:
      - name: cartsloadgen
        image: docker.io/keptnexamples/cartsloadgenerator:0.1
        imagePullPolicy: Always
